### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by LiMufeng123** [Dawit1922/Modified-DarkCovidNet#1]
hello，I am interested in your research,but I come up with some problems.Is you code forgetting to import some package?for example :

```
path = Path('/content/gdrive/My Drive/COVID-19-master/COVID-19-master/X-Ray Image DataSet')
#Save the path of dataset location in the Path() object.
path = Path('/content/gdrive/My Drive/COVID-19-master/COVID-19-master/X-Ray Image DataSet')
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_27/1352399251.py in <module>
      1 #Save the path of dataset location in the Path() object.
----> 2 path = Path('/content/gdrive/My Drive/COVID-19-master/COVID-19-master/X-Ray Image DataSet')

NameError: name 'Path' is not defined

can you give me the total code?Thanks a lot!

**Comment by LiMufeng123** [comment]
Your valid foder also is your test folder,that is so funny!!!

**Comment by Dawit1922** [comment]
Hi Lei, I hope you have solved the issue. I was using fast ai library. i didn't have to explicitly import Path as it was included in the library. I am sorry for interchangeably using test and valid. I have corrected it later.
